### ISSUE TITLE
关于Vue2.0的过渡效果与过渡状态

### ISSUE THREAD

**Issue by bluezhan** [itemsets/vue2#2]
### 前言 

因为是MVVM模式，加上又是单页面应用，会考虑到页面的切换过渡效果和各种组件、控件、插件的界面动态切换效果。固然就会在这一块加入概念和处理方式。

大概的处理方式就是：

- CSS3.0的动画
- JavaScript的处理

看一下官方[过渡效果](https://vuefe.cn/guide/transitions.html) 

通过 Vue 2.0 的过渡系统， 在插入、更新或者移除 `DOM` 时，提供多种不同方式的应用过渡效果。
包括以下工具：

- 在 `CSS` 过渡和动画中自动应用 `class`
- 可以配合使用第三方 `CSS` 动画库，如 `Animate.css`
- 在过渡钩子函数中使用 `JavaScript` 直接操作 `DOM`
- 可以配合使用第三方 `JavaScript` 动画库，如 `Velocity.js`
- 在这里，我们只会讲到进入、离开和列表的过渡， 你也可以看下一节的 [管理过渡状态](https://vuefe.cn/guide/transitioning-state.html).

### 单元素/组件的过渡

贴个例子：
```html
<div id="demo">
  <button v-on:click="show = !show">
    点击我切换（Toggle）
  </button>
  <transition name="fade">
    <p v-if="show">我就是个动画</p>
  </transition>
</div>
```
```css
.fade-enter-active, .fade-leave-active {
  transition: opacity .5s
}
.fade-enter, .fade-leave-active {
  opacity: 0
}
```
```js
new Vue({
  el: '#demo',
  data: {
    show: true
  }
})
```

在上面的案例，会发现：有个 `transition` 的封装元素，而且还会发生CSS的类的命名格式。

Vue 2.0 提供了 `transition` 的封装组件，在下列情形中，可以给任何元素和组件添加 `entering/leaving` 过渡

- 条件渲染 （使用 `v-if`）
- 条件展示 （使用 `v-show`）
- 循环语句 （使用 `v-for`；只在插入和删除时触发，使用 `vue-animated-list` 插件）
- 动态组件 （数据驱动组件过渡）
- 组件根节点 （组件的根节点上，并且被 Vue2.0 实例 `DOM` 方法（如 `vm.$appendTo(el)`）触发。）

在 transition 的封装元素里有个`name`属性并赋了值 fade ；上面说得很明白了，__可以给任何元素和组件添加 `entering/leaving` 过渡__。这个时候去瞄一下CSS的类命名就完全明白了。

本来这里作者是想封装个基本动画的；最后是没必要的，所以需要自己添加，也可以引入动画库和插件。

__这里应该还涉及到  `transition` 的封装组件的状态和处理机制，这才是好玩的东西，也是个重点。下面讲到，[点击我吧。](https://github.com/program-management/Vue2.0/issues/3)__

我们先来看一段Vue2.0源码：

```js
// 这是切换CSS的类命名
var autoCssTransition = cached(function (name) {
  return {
    enterClass: (name + "-enter"),
    leaveClass: (name + "-leave"),
    appearClass: (name + "-enter"),
    enterActiveClass: (name + "-enter-active"),
    leaveActiveClass: (name + "-leave-active"),
    appearActiveClass: (name + "-enter-active")
  }
});
  // 开始 enter 的 transition 
  beforeEnterHook && beforeEnterHook(el);
  if (expectsCSS) {
    addTransitionClass(el, startClass);
    addTransitionClass(el, activeClass);
    nextFrame(function () {
      removeTransitionClass(el, startClass);
      if (!cb.cancelled && !userWantsControl) {
        whenTransitionEnds(el, type, cb);
      }
    });
  }
 // 触发 leave 的 transition 
  if (expectsCSS) {
      addTransitionClass(el, leaveClass);
      addTransitionClass(el, leaveActiveClass);
      nextFrame(function () {
        removeTransitionClass(el, leaveClass);
        if (!cb.cancelled && !userWantsControl) {
          whenTransitionEnds(el, type, cb);
        }
      });
    }

```

从上面看出来添加了`startClass`接着就是删除了它，初始化元素的状态并集合 `transition` 的封装组件的状态和处理机制。

看官方解析：

元素封装成过渡组件之后，在遇到插入或删除时，Vue 2.0 将

- 自动嗅探目标元素是否有 CSS 过渡或动画，并在合适时添加/删除 CSS  类名。
- 如果过渡组件设置了过渡的 JavaScript 钩子函数，会在相应的阶段调用钩子函数。
- 如果没有找到 JavaScript 钩子并且也没有检测到 CSS 过渡/动画，`DOM` 操作（插入/删除）在下一帧中立即执行。(注意：此指浏览器逐帧动画机制，与 Vue 2.0，和 Vue 2.0 的 nextTick 概念不同)

__过渡的-CSS-类名__

会有 4 个(CSS)类名在 enter/leave 的过渡中切换

- v-enter: 定义进入过渡的开始状态。在元素被插入时生效，在下一个帧移除。
- v-enter-active: 定义进入过渡的结束状态。在元素被插入时生效，在 `transition/animation` 完成之后移除。
- v-leave: 定义离开过渡的开始状态。在离开过渡被触发时生效，在下一个帧移除。
- v-leave-active: 定义离开过渡的结束状态。在离开过渡被触发时生效，在 `transition/animation`完成之后移除。

![transition](https://cloud.githubusercontent.com/assets/16684336/20166469/efa39bec-a74f-11e6-833b-efe922322aa2.png)

对于这些在 enter/leave 过渡中切换的类名，v- 是这些类名的前缀。使用 `<name="my-transition>"` 可以重置前缀，比如 `v-enter` 替换为 `my-transition-enter`。

`v-enter-active` 和 `v-leave-active` 可以控制 进入/离开 过渡的不同阶段，在下面章节会有个示例说明。

> __不过看起来是很复杂的，我就简单说上几句：__
   - v-enter: 就是元素插入时的初始化状态，自己爱咋样定义就咋样定义，不过在下一个帧移除。
  - v-enter-active:  就是和`v-enter`在下一行代码插入的，不过它是在 `transition/animation` 完成之后移除的。
  - v-leave: 被触发离开时生效，在下一个帧移除。基本这个鬼是用不到的。
  - v-leave-active:  就是和`v-leave`在下一行代码插入的，在 `transition/animation`完成之后移除。

__其实如果感觉到很困惑的话，一定是对DOM插入状态和CSS3.0动画的理解不彻底。__

_有时候去看看源码就很明白很清楚了_

**Comment by bluezhan** [comment]
### 添加CSS 3.0 动画

在上面的例子里什么都没变就是修改的样式的调用，改用了CSS3.0的[ `animation`](http://www.w3school.com.cn/cssref/pr_animation.asp) 动画。

``` css
.bounce-enter-active {  animation: bounce-in .5s; }
.bounce-leave-active {  animation: bounce-out .5s; }
@keyframes bounce-in {
  0% {  transform: scale(0); }
  50% {  transform: scale(1.5); }
  100% {  transform: scale(1); }
}
@keyframes bounce-out {
  0% {  transform: scale(1); }
  50% {  transform: scale(1.5); }
  100% {  transform: scale(0); }
}
```

### 自定义过渡类名

我们可以通过以下特性来自定义过渡类名：
- enter-class
- enter-active-class
- leave-class
- leave-active-class
  他们的优先级高于普通的类名，这对于 Vue 的过渡系统和其他第三方 CSS 动画库，如 [Animate.css](https://daneden.github.io/animate.css/) 结合使用十分有用。

``` html
 <transition
    name="custom-classes-transition"
    enter-active-class="animated tada"
    leave-active-class="animated bounceOutRight"
  >
    <p v-if="show">hello</p>
  </transition>
```

### 同时使用 Transitions 和 Animations

Vue 2.0  为了知道过渡的完成，必须设置相应的事件监听器。它可以是`transitionend` 或 `animationend` ，这取决于给元素应用的 CSS 规则。如果你使用其中任何一种，Vue 2.0 能自动识别类型并设置监听。

但是，在一些场景中，你需要给同一个元素同时设置两种过渡动效，比如 `animation` 很快的被触发并完成了，而`transition` 效果还没结束。在这种情况中，你就需要使用 `type`特性并设置 `animation` 或 `transition` 来明确声明你需要 Vue 2.0 监听的类型。

**官方没有给出例子，而且不一目了然。**

给同一个元素同时设置两种过渡动效`animation` 和 `transition` ；它们的是同时执行的。

``` css
    .fade-enter-active ,
    .fade-leave-active {
        animation: bounce-in 1.5s;
        transition: opacity .5s;
    }
```

``` html
   <transition name="fade" type="animation">
         <p v-if="show">我就是个动画</p>
   </transition>
```

看到没，就是`transition`的属性`type`处理了。
